apiVersion: v1
kind: Namespace
metadata:
  name: <insert-namespace-name-here>

---

apiVersion: v1
kind: Secret
metadata:
  namespace: <name-space>
  name: regcred
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: >-
    <base64>

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: <name-space>
  name: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello
          image: <your-image-name>
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  namespace: <name-space>
  name: hello
spec:
  selector:
    app: hello
  ports:
    - port: 8080
      targetPort: 80
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: <name-space>
  name: http-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - http:
        paths:
          - path: /<your-path>(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: hello
                port:
                  number: 8080