apiVersion: v1
kind: Namespace
metadata:
  name: hello

---

apiVersion: v1
kind: Secret
metadata:
  namespace: hello
  name: regcred
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: >-
    ewogICJhdXRocyI6ewogICAgInJlZ2lzdHJ5LmdpdGxhYi5jb20iOnsKICAgICAgInVzZXJuYW1lIjoic29tbWFpLmtAZ21haWwuY29tIiwKICAgICAgInBhc3N3b3JkIjoibmV3UG5QIzIwMDMiLAogICAgICAiZW1haWwiOiJzb21tYWkua0BnbWFpbC5jb20iCiAgICB9CiAgfQp9

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hello
  name: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello
          image: registry.gitlab.com/sommai.k/imc-devops-07/hello
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  namespace: hello
  name: hello
spec:
  selector:
    app: hello
  ports:
    - port: 8080
      targetPort: 80
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: hello
  name: http-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - http:
        paths:
          - path: /hello(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: hello
                port:
                  number: 8080