services:

  jenkinsmaster:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
  
  mssql:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "new#Mssql001"
    ports:
      - 1433:1433
    volumes:
      - mssql_data:/var/opt/mssql
  
  sonarqube:
    image: sonarqube:community
    restart: always
    depends_on:
      - sonar_db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar_db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp
  sonar_db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - sonar_db:/var/lib/postgresql
      - sonar_db_data:/var/lib/postgresql/data
  dbeaver:
    image: dbeaver/cloudbeaver
    restart: always
    volumes:
      - dbeaver_data:/opt/cloudbeaver/workspace
    ports:
      - 8978:8978

volumes:
  jenkins_home:
  mssql_data:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:
  sonar_db:
  sonar_db_data:
  dbeaver_data:
