FROM jenkins/agent:latest
USER root
RUN apt-get update && \
    apt-get install -y python3-full && \
    rm -rf /var/lib/apt/lists/*
# RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 100 && \
#     update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 100

USER jenkins
